import Head from 'next/head';
import MainLayout from '@/layout/MainLayout';
import InfobaseTable from '@/components/InfobaseTable';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <MainLayout isChatUI={false}>
          <InfobaseTable
            data={[
              {
                id: '987',
                docType: 'Testimony',
                docName: 'Electric Panel',
                sentiment: 'Positive',
                author: 'ConEd',
                dateUploaded: '06/01/2023',
                privacy: 'Public',
                docSummary: 'Consolidated Edison Company of new York.Inc',
                status: 'Ingestied',
              },
              {
                id: '991',
                docType: 'Testimony',
                docName: 'Electric Panel',
                sentiment: 'Positive',
                author: 'ConEd',
                dateUploaded: '06/07/2023',
                privacy: 'Public',
                docSummary: 'Consolidated Edison Company of new York.Inc',
                status: 'Ingestied',
              },
              {
                id: '992',
                docType: 'Exhibit',
                docName: 'Gas Panel',
                sentiment: 'Negative',
                author: 'LRP',
                dateUploaded: '06/12/2023',
                privacy: 'Public',
                docSummary: 'This reports providers a competitive analysis',
                status: 'Pending',
              },
              {
                id: '0',
                docType: 'Exhibit',
                docName: 'Gas Panel',
                sentiment: 'Negative',
                author: 'LRP',
                dateUploaded: '06/12/2023',
                privacy: 'Public',
                docSummary: 'This reports providers a competitive analysis',
                status: 'Pending',
              },
            ]}
          />
        </MainLayout>
      </main>
    </>
  );
}
